development:
  sessions:
    default:
      uri: mongodb://asquerosito_dev:4squ3r0s1t0@ds033757.mongolab.com:53818/asquerosito_dev

test:
  sessions:
    default:
      uri: mongodb://asquerosito_dev:4squ3r0s1t0@ds033757.mongolab.com:53818/asquerosito_dev

production:
  sessions:
    default:
      hosts: 
        - <%= JSON.parse(ENV['VCAP_SERVICES'])['mongodb-1.8'].first['credentials']['hostname'] rescue 'ds033757.mongolab.com' %>:<%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-1.8'].first['credentials']['port'] rescue 33757 %>
      username: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-1.8'].first['credentials']['username'] rescue 'asquerosito_dev' %>
      password: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-1.8'].first['credentials']['password'] rescue '4squ3r0s1t0' %>
      database:  <%= JSON.parse( ENV['VCAP_SERVICES'] )['mongodb-1.8'].first['credentials']['db'] rescue 'asquerosito_dev' %>